# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e547b84c8f95ae0d77fa424770067049043105a90e1a14c188c91c63ff1573e65864ba6954504cb86751a0cc656c696b8becb2332290a91c4a3672cdde3ba6b

test:
  secret_key_base: 1e3f7d014e4df8adbf884b3e865168780f6d61759c3978bfdc80ded27b9649b9c944b284e3ee34489d8329cf1f396ef92ef577a159ff0bbff021a3e27052657e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
